nfidd/ueifid

sessions/forecast-visualisation.qmd, sessions/slides/forecasting-as-an-epidemiological-problem.qmd, sessions/ueifid.bib
=> visualisation session

getting-set-up.qmd
https://github.com/nfidd/nfidd/pull/362
=> clarify copy & paste option

sessions/forecast-ensembles.qmd, sessions/slides/introduction-to-ensembles.qmd
=> ensemble session

learning_objectives.qmd
we're not covering some of the currently listed ones
=> update learning objectives

sessions/forecast-ensembles.qmd, sessions/forecast-visualisation.qmd, sessions/slides/introduction-to-the-course-and-the-instructors.qmd
Read through up to the end of forecast vis with edits + adding optional model detail for all models.
=> Read through up to forecast vis

sessions.qmd
=> Add a session to evaluate multiple models

.github/workflows/deploy.yaml, .github/workflows/render-readme.yaml, sessions/forecast-ensembles.qmd
=> update package name to qrensemble

sessions/forecast-evaluation-of-multiple-models.qmd
As per the title. This mainly draws on the nfidd multiple models session with some light refactoring
=> Add multiple evaluation content to course

getting-set-up.qmd
=> Adds a new repo to pak for additional repositories

sessions/slides/introduction-to-the-course-and-the-instructors.qmd
stretch all images to column width
also fixes formatting on bullet points earlier in the session
=> make Seb bigger

sessions/introduction-and-course-overview.qmd
it's already earlier in the session
=> remove duplicate link

sessions/slides/introduction-to-the-course-and-the-instructors.qmd
as its in the material already. This is also currently broken so if we don't remove need to fix the formatting.
=> Removes the duplication of approach from the slides

sessions/forecast-evaluation-of-multiple-models.qmd, sessions/forecast-evaluation.qmd, sessions/ueifid.bib
- more explanation on absolute scales of CRPS
- avoid double "score" when saying CRPS scores
- turn Bosse et al. into a reference
=> light evaluation edits

sessions/forecast-evaluation-of-multiple-models.qmd
=> Update forecast-evaluation-of-multiple-models.qmd intro 

sessions/forecast-visualisation.qmd
=> clarify relationship with other course

.github/workflows/deploy.yaml, .github/workflows/render-readme.yaml, getting-set-up.qmd
also updated back to default CRAN mirror to be safe(r)
=> use r-universe (and CRAN)

sessions/forecast-ensembles.qmd
typos, adding WIS relationship to CRPS, and removing empty sections
=> Edits to forecast ensembles

sessions/slides/closing.qmd
Typos, adds new session, uses image that exists
=> Edits to closing talk

sessions.qmd
=> fix timetable

sessions/forecast-evaluation-of-multiple-models.qmd
=> removed unused libraries

sessions/slides/introduction-to-the-spectrum-of-forecasting-models.qmd
=> fix your turn for multiple forecast models
